#!/usr/bin/env python
import sys, os, warnings
with warnings.catch_warnings():
    warnings.filterwarnings("ignore",category=DeprecationWarning)
    import imp
tests_dir = os.path.dirname(os.path.abspath(__file__))
compile_dir = os.path.dirname(tests_dir)
sys.path.insert(0, compile_dir)
cwd = os.path.realpath(os.getcwd())
try:
	import coverage
	coverage.the_coverage.parallel_mode = True
	coverage.start()
except:
	coverage = None
os.chdir(cwd)
compile_code = os.path.join(compile_dir, '0compile')
try:
	class DummyStream():
		def read(self):
			pass
		def close(self):
			pass
	from urllib import request
	def cb(*args):
		print("urlopen called with arguments %s" % (args,), file=sys.stderr)
		return DummyStream()
	request.urlopen = cb
	with open(compile_code) as stream:
		imp.load_module('__main__', stream, compile_code,
				('.py', 'r', imp.PY_SOURCE))
finally:
	if coverage:
		coverage.stop()
