#!/usr/bin/env python
import sys, imp, os
tests_dir = os.path.dirname(os.path.abspath(__file__))
compile_dir = os.path.dirname(tests_dir)
sys.path.insert(0, compile_dir)
cwd = os.path.realpath(os.getcwd())
os.chdir(tests_dir)
try:
	import coverage
	coverage.the_coverage.parallel_mode = True
	coverage.start()
except:
	coverage = None
os.chdir(cwd)
compile_code = os.path.join(compile_dir, '0compile')
try:
	imp.load_module('__main__', file(compile_code), compile_code,
			('.py', 'r', imp.PY_SOURCE))
finally:
	os.chdir(tests_dir)
	if coverage:
		coverage.stop()
