#!/usr/bin/env python
import sys, os
print "hello2"
with open(os.path.join(os.environ['ROXLIB'], 'rox', '__init__.py'), 'r') as stream:
	for line in stream:
		if line.startswith('roxlib_version = '):
			print "Using ROX-Lib: " + line
